# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Building container
        run: docker build -t my-apache2
      - name: run Docker
        run: docker run -d -p 80:80 --name docker-apache -d my-apache2
      - name: check server
        run: curl http://localhost:80
      - name: Install Google Chrome
        run:  |
               chmod +x ./InstallChrome.sh
               ./InstallChrome.sh
      - name: Check out Selenium Script
        uses: actions/checkout@main
        with:
          repository: deevsky69/testingCICD
          path: './testingCICD'
      - name: Show Working directory
        run: ls
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Run Selenium Script
        run: |
              cd ./testingCICD
              mvn test
      - name: Stop Docker
        run: docker stop docker-apache





      # - name: Checkout the repo
      #   uses: actions/checkout@v3
      # - name: Building Container
      #   run: docker build -t my-apache2 .
      # - name: run Docker
      #   run: docker run -d -p 80:80 --name docker-apache -d my-apache2
      # - name: check server
      #   run: curl http://localhost:80
      # - name: Stop Docker
      #   run: docker stop docker-apache






    # - name: Checkout the repo
    #   uses: actions/checkout@v3
    # - name: Install Google Chrome
    #   run : |
    #          chmod +x ./InstallChrome.sh
    #          ./InstallChrome.sh
    # - name: Check out Selenium Script
    #   uses: actions/checkout@main
    #   with:
    #     repository: deevsky69/testingCICD
    #     path: './testingCICD'
    # - name: Show Working directory
    #   run: ls
    # - name: Set up JDK 11
    #   uses: actions/setup-java@v3
    #   with:
    #     java-version: '11'
    #     distribution: 'temurin'
    #     cache: maven
    # - name: Run Selenium Script
    #   run: |
    #         cd ./testingCICD
    #         mvn test




    # - uses: actions/checkout@v3
    # - name: Set up JDK 11
    #   uses: actions/setup-java@v3
    #   with:
    #     java-version: '11'
    #     distribution: 'temurin'
    #     cache: maven
    # - name: Build with Maven
    #   run: mvn -B package --file pom.xml

    # # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # - name: Update dependency graph
    #   uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
